version: '3.3'

services:
  dbute:
    image: postgres:13
    environment:
      - POSTGRES_DB=db_ute
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - ./databaseData:/var/lib/postgresql/data